# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto.proto",
    package="demo",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0bproto.proto\x12\x04\x64\x65mo";\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t"E\n\x07\x43ontact\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tperson_id\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t"\x16\n\x08PersonId\x12\n\n\x02id\x18\x01 \x01(\x03"S\n\x12\x46ullPersonResponse\x12\x1c\n\x06person\x18\x01 \x01(\x0b\x32\x0c.demo.Person\x12\x1f\n\x08\x63ontacts\x18\x02 \x03(\x0b\x32\r.demo.Contact2\xa5\x01\n\x0b\x41\x64\x64ressBook\x12,\n\x0c\x43reatePerson\x12\x0c.demo.Person\x1a\x0c.demo.Person"\x00\x12\x37\n\tGetPerson\x12\x0e.demo.PersonId\x1a\x18.demo.FullPersonResponse"\x00\x12/\n\rCreateContact\x12\r.demo.Contact\x1a\r.demo.Contact"\x00\x62\x06proto3',
)


_PERSON = _descriptor.Descriptor(
    name="Person",
    full_name="demo.Person",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="demo.Person.id",
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="first_name",
            full_name="demo.Person.first_name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="last_name",
            full_name="demo.Person.last_name",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=21,
    serialized_end=80,
)


_CONTACT = _descriptor.Descriptor(
    name="Contact",
    full_name="demo.Contact",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="demo.Contact.id",
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="person_id",
            full_name="demo.Contact.person_id",
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="type",
            full_name="demo.Contact.type",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="demo.Contact.value",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=82,
    serialized_end=151,
)


_PERSONID = _descriptor.Descriptor(
    name="PersonId",
    full_name="demo.PersonId",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="demo.PersonId.id",
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=153,
    serialized_end=175,
)


_FULLPERSONRESPONSE = _descriptor.Descriptor(
    name="FullPersonResponse",
    full_name="demo.FullPersonResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="person",
            full_name="demo.FullPersonResponse.person",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="contacts",
            full_name="demo.FullPersonResponse.contacts",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=177,
    serialized_end=260,
)

_FULLPERSONRESPONSE.fields_by_name["person"].message_type = _PERSON
_FULLPERSONRESPONSE.fields_by_name["contacts"].message_type = _CONTACT
DESCRIPTOR.message_types_by_name["Person"] = _PERSON
DESCRIPTOR.message_types_by_name["Contact"] = _CONTACT
DESCRIPTOR.message_types_by_name["PersonId"] = _PERSONID
DESCRIPTOR.message_types_by_name["FullPersonResponse"] = _FULLPERSONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Person = _reflection.GeneratedProtocolMessageType(
    "Person",
    (_message.Message,),
    {
        "DESCRIPTOR": _PERSON,
        "__module__": "proto_pb2"
        # @@protoc_insertion_point(class_scope:demo.Person)
    },
)
_sym_db.RegisterMessage(Person)

Contact = _reflection.GeneratedProtocolMessageType(
    "Contact",
    (_message.Message,),
    {
        "DESCRIPTOR": _CONTACT,
        "__module__": "proto_pb2"
        # @@protoc_insertion_point(class_scope:demo.Contact)
    },
)
_sym_db.RegisterMessage(Contact)

PersonId = _reflection.GeneratedProtocolMessageType(
    "PersonId",
    (_message.Message,),
    {
        "DESCRIPTOR": _PERSONID,
        "__module__": "proto_pb2"
        # @@protoc_insertion_point(class_scope:demo.PersonId)
    },
)
_sym_db.RegisterMessage(PersonId)

FullPersonResponse = _reflection.GeneratedProtocolMessageType(
    "FullPersonResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _FULLPERSONRESPONSE,
        "__module__": "proto_pb2"
        # @@protoc_insertion_point(class_scope:demo.FullPersonResponse)
    },
)
_sym_db.RegisterMessage(FullPersonResponse)


_ADDRESSBOOK = _descriptor.ServiceDescriptor(
    name="AddressBook",
    full_name="demo.AddressBook",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=263,
    serialized_end=428,
    methods=[
        _descriptor.MethodDescriptor(
            name="CreatePerson",
            full_name="demo.AddressBook.CreatePerson",
            index=0,
            containing_service=None,
            input_type=_PERSON,
            output_type=_PERSON,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="GetPerson",
            full_name="demo.AddressBook.GetPerson",
            index=1,
            containing_service=None,
            input_type=_PERSONID,
            output_type=_FULLPERSONRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="CreateContact",
            full_name="demo.AddressBook.CreateContact",
            index=2,
            containing_service=None,
            input_type=_CONTACT,
            output_type=_CONTACT,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_ADDRESSBOOK)

DESCRIPTOR.services_by_name["AddressBook"] = _ADDRESSBOOK

# @@protoc_insertion_point(module_scope)
