# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_pb2 as proto__pb2


class AddressBookStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePerson = channel.unary_unary(
            "/demo.AddressBook/CreatePerson",
            request_serializer=proto__pb2.Person.SerializeToString,
            response_deserializer=proto__pb2.Person.FromString,
        )
        self.GetPerson = channel.unary_unary(
            "/demo.AddressBook/GetPerson",
            request_serializer=proto__pb2.PersonId.SerializeToString,
            response_deserializer=proto__pb2.FullPersonResponse.FromString,
        )
        self.CreateContact = channel.unary_unary(
            "/demo.AddressBook/CreateContact",
            request_serializer=proto__pb2.Contact.SerializeToString,
            response_deserializer=proto__pb2.Contact.FromString,
        )


class AddressBookServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AddressBookServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreatePerson": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePerson,
            request_deserializer=proto__pb2.Person.FromString,
            response_serializer=proto__pb2.Person.SerializeToString,
        ),
        "GetPerson": grpc.unary_unary_rpc_method_handler(
            servicer.GetPerson,
            request_deserializer=proto__pb2.PersonId.FromString,
            response_serializer=proto__pb2.FullPersonResponse.SerializeToString,
        ),
        "CreateContact": grpc.unary_unary_rpc_method_handler(
            servicer.CreateContact,
            request_deserializer=proto__pb2.Contact.FromString,
            response_serializer=proto__pb2.Contact.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "demo.AddressBook", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AddressBook(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePerson(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/demo.AddressBook/CreatePerson",
            proto__pb2.Person.SerializeToString,
            proto__pb2.Person.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetPerson(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/demo.AddressBook/GetPerson",
            proto__pb2.PersonId.SerializeToString,
            proto__pb2.FullPersonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CreateContact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/demo.AddressBook/CreateContact",
            proto__pb2.Contact.SerializeToString,
            proto__pb2.Contact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
